FROM kong:latest

# Kong install dir
ENV KONG_HOME /usr/local/share/lua/5.1/kong

ADD ./kong-oidc-auth /usr/local/share/lua/5.1/kong/plugins/kong-oidc-auth
RUN apk -U add git unzip gcc libc-dev openssl-dev
RUN (cd $KONG_HOME/plugins/kong-oidc-auth/ && luarocks make *.rockspec)

